<?xml version="1.0"?>
<package format="3">
  <name>my_nav2_demo</name>
  <version>0.0.1</version>
  <description>Phase 22A: Nav2 stack on TurtleBot3 + slam_toolbox map.</description>
  <maintainer email="gino.tsai@goodlinker.io">gino</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>my_gazebo_demo</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
