<?xml version="1.0"?>
<package format="3">
  <name>my_pcl_demo</name>
  <version>0.0.1</version>
  <description>Advanced/perception 04: PCL pipeline (VoxelGrid + RANSAC plane + Euclidean clustering)</description>
  <maintainer email="gino.tsai@goodlinker.io">gino</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>vision_msgs</depend>
  <depend>pcl_conversions</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
